[tool.black]
line-length = 88

[tool.isort]
profile = "black"
skip_glob = ".venv"

[tool.mypy]
exclude = ".venv/"
check_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_subclassing_any = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true

[tool.poetry]
name = "<project-name>"
version = "0.1.0"
description = "<project-description>"
authors = ["Gary Prescott <gary@madplum.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "<project_name>"}]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
black = "^22.12.0"
flake8 = "^6.0.0"
mypy = "^1.0"
pytest-cov = "^4.0.0"
flake8-isort = "^6.0.0"
isort = "^5.11.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
